### ISSUE TITLE
Further customization

### ISSUE THREAD

**Issue by cyrilchapon** [Zmetser/angular-currency-filter#4]
In here, we display currency like "10 000,20€" or "10000,20€" but not like "10,000.00€".

One should be able to customize the "thousand separator char" and the "decimal separator char".

**Comment by vroudge** [comment]
Agree

**Comment by Zmetser** [comment]
Sorry for the very late response and thank you for your suggestion, I'll provide the requested options in the next release, later this week.

**Comment by vroudge** [comment]
Hey! Thank you very much :)

**Comment by Zmetser** [comment]
From v2.1.0 you can customize group and decimal separators
```javascript
var formats = {
  GROUP_SEP: ' ',
  DECIMAL_SEP: ','
};
expect(currency(10000.201, '€', 2, true, formats)).toEqual('10 000,20€');
```

```javascript
var formats = {
  GROUP_SEP: '', // Passing an empty string will get rid of the group separator
  DECIMAL_SEP: ','
};
expect(currency(10000.201, '€', 2, true, formats)).toEqual('10000,20€');
```

**Comment by cyrilchapon** [comment]
Awesome
