### ISSUE TITLE
display is number 0 when variable return is null

### ISSUE THREAD

**Issue by dtagdev1** [Zmetser/angular-currency-filter#5]
when variable return is null, data have been display is none.
I think, should display is number 0

**Comment by Zmetser** [comment]
I guess that makes more sense then returning an empty string. I'll do it tomorrow. Thanks.

**Comment by Zmetser** [comment]
Fixed in [v2.0.0](https://github.com/Zmetser/angular-currency-filter/tree/v2.0.0)

**Comment by Zmetser** [comment]
Fixed in [v2.0.0](https://github.com/Zmetser/angular-currency-filter/tree/v2.0.0)

**Comment by dtagdev1** [comment]
Thank @Zmetser
