### ISSUE TITLE
Allow suffix string value

### ISSUE THREAD

**Issue by brophdawg11** [Zmetser/angular-currency-filter#9]
Great library!  Just looking for one additional bit of functionality.

I have UX requirements to display both a custom symbol as well as a string suffix on prices under certain scenarios.  The main example of this is to distinguish between currencies sharing the same symbol, such as USD/CAD/AUD.  Allowing the specification of an optional suffix string would support displays such as:

```
$100.00 USD
$100.00 CAD
$100.00 AUD
```

I have a PR I will submit that will support this if `suffixSymbol` is passed as a string instead of a boolean.

**Comment by Zmetser** [comment]
That all makes sense, thanks for the PR!
